// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoodsList(arg1, arg2) {
  return window['go']['service']['Service']['GoodsList'](arg1, arg2);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['service']['Service']['Login'](arg1, arg2, arg3);
}

export function OrderList(arg1, arg2) {
  return window['go']['service']['Service']['OrderList'](arg1, arg2);
}
