// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {resp} from '../models';
import {req} from '../models';

export function BusinessAdd(arg1:string,arg2:string):Promise<resp.Response>;

export function BusinessList(arg1:string,arg2:number,arg3:number):Promise<resp.Response>;

export function GoodsAdd(arg1:req.GoodsAddReq):Promise<resp.Response>;

export function GoodsList(arg1:string,arg2:number,arg3:number):Promise<resp.Response>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<resp.Response>;

export function OrderList(arg1:string,arg2:string):Promise<resp.Response>;
