// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoodsList(arg1:string,arg2:string):Promise<any>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<any>;

export function OrderList(arg1:string,arg2:string):Promise<any>;
